### ISSUE TITLE
使用tabs空指针问题

### ISSUE THREAD

**Issue by danna88** [listenzz/react-native-navigation-hybrid#131]
代码：
Navigator.setRoot({
  tabs: {
    children: [
      {
        stack: {
          children: [{ screen: { moduleName: 'aScreen' } }],
        },
      },
      {
        stack: {
          children: [{ screen: { moduleName: 'bScreen' } }],
        },
      },
    ],
    options: {
      selectedIndex: 0, // 默认选中的 tab
    },
  },
});

在页面内部设置了title：
static navigationItem = {
    titleItem: {
      // 导航栏标题
      title: '这是标题',
    },
    tabItem: {
      title: '登录',
    },
  };

启动后，一直空指针：

**Comment by danna88** [comment]
上传不了图片，错误如下：
java.lang.NullPointerException
        at me.listenzz.navigation.TabBar.bindTabWithData(TabBar.java:309)
        at me.listenzz.navigation.TabBar.setupTab(TabBar.java:215)
        at me.listenzz.navigation.TabBar.initialise(TabBar.java:173)
        at me.listenzz.navigation.DefaultTabBarProvider.initialise(DefaultTabBarProvider.java:83)
        at me.listenzz.navigation.DefaultTabBarProvider.onCreateTabBar(DefaultTabBarProvider.java:25)
        at me.listenzz.navigation.TabBarFragment.onViewCreated(TabBarFragment.java:89)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2646)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2416)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2372)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:814)
        at me.listenzz.navigation.FragmentHelper.executePendingTransactionsSafe(FragmentHelper.java:37)
        at me.listenzz.navigation.AwesomeActivity.setRootFragmentInternal(AwesomeActivity.java:104)
        at com.navigationhybrid.ReactAppCompatActivity.setRootFragmentInternal(ReactAppCompatActivity.java:105)
        at me.listenzz.navigation.AwesomeActivity.setActivityRootFragment(AwesomeActivity.java:89)
        at com.navigationhybrid.ReactAppCompatActivity.setActivityRootFragment(ReactAppCompatActivity.java:94)
        at com.navigationhybrid.NavigationModule.lambda$setRoot$3$NavigationModule(NavigationModule.java:117)

**Comment by listenzz** [comment]
tabItem: {
title: '登录',
}, 

少了 icon

**Comment by danna88** [comment]
喔，必须要icon吗，这个能不能兼容下，因为icon不是必须的吧，做demo

**Comment by listenzz** [comment]
0.17.11 开始，icon 不是必须的。
